2024-10-29 11:57:54,460 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 11:58:30,808 - root - INFO - User None (554980782) used /start
2024-10-29 11:59:46,387 - root - INFO - User None (554980782) used /start
2024-10-29 12:00:18,177 - root - INFO - User None (554980782) used /start
2024-10-29 12:00:40,629 - root - INFO - User None (554980782) used /start
2024-10-29 12:03:51,362 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 12:04:04,877 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 14:46:59,137 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 14:47:12,196 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 14:47:18,741 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 14:49:19,726 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 15:32:29,574 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 15:33:08,603 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 15:34:23,079 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 15:39:59,764 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 15:42:44,962 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 15:43:19,493 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 15:56:22,296 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 15:59:53,979 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 16:07:38,769 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 16:19:06,279 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 16:34:59,372 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 17:40:00,786 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 17:43:40,789 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 17:49:02,121 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 17:49:21,584 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 17:53:43,681 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 17:54:22,165 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 17:55:14,427 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:02:43,114 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:07:21,735 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:12:28,034 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:13:34,610 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:16:37,615 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:18:26,255 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:22:18,971 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:23:01,263 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:24:55,356 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:29:54,334 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:31:08,494 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:32:25,763 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:33:56,495 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:35:02,785 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:35:08,956 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:42:52,844 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:43:41,117 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:45:09,115 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:45:50,587 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:48:03,746 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:48:56,490 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:49:46,231 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:51:45,346 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 18:56:37,843 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:00:08,232 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:02:27,538 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:03:57,112 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:06:26,388 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:06:54,472 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:07:04,299 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:08:20,344 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:09:10,978 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:10:15,840 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:10:23,151 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:17:47,712 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:19:11,025 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:19:17,029 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:20:45,675 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:23:42,281 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:23:56,184 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:25:09,623 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:35:56,421 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:36:26,711 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:44:02,646 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:46:45,411 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:47:38,891 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:49:47,858 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:51:17,286 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 19:51:35,842 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 20:01:09,629 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 20:01:47,458 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 20:02:01,601 - root - INFO - User Legend_kr (479851312) used /start
2024-10-29 20:02:16,016 - root - INFO - User Legend_kr (479851312) used /start
2024-10-30 14:02:47,081 - root - INFO - User Legend_kr (479851312) used /start
2024-10-30 14:04:41,096 - root - INFO - User Legend_kr (479851312) used /start
2024-10-30 14:10:08,102 - root - INFO - User Legend_kr (479851312) used /start
2024-10-30 14:13:55,426 - root - INFO - User Legend_kr (479851312) used /start
2024-10-30 14:14:38,950 - root - INFO - User Legend_kr (479851312) used /start
2024-10-30 14:21:51,429 - root - INFO - User Legend_kr (479851312) used /start
2024-10-30 14:37:36,358 - root - INFO - User Legend_kr (479851312) used /start
2024-10-30 15:33:06,624 - root - INFO - User Legend_kr (479851312) used /start
2024-10-30 16:11:12,427 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 13:59:22,125 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 14:04:38,604 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 14:18:28,778 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 14:23:23,814 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 14:24:00,113 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 15:12:29,271 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 15:17:33,674 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 15:18:32,545 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 15:18:58,759 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 15:21:36,993 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 15:23:26,224 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 15:30:04,211 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 18:49:29,938 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 18:51:54,160 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 18:54:47,315 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 18:55:23,226 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 19:01:14,627 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:01:14,628 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:01:17,998 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:01:17,998 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:01:18,358 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:01:18,358 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:01:21,972 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:01:21,973 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:01:22,595 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:01:22,596 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:01:26,721 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:01:26,721 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:01:27,835 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:01:27,836 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:01:32,956 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:01:32,957 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:01:35,069 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:01:35,070 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:01:39,193 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:01:39,193 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:01:43,319 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:01:43,320 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:01:51,432 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:01:51,433 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:01:59,572 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:01:59,573 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:02:15,695 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:02:15,695 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:02:31,821 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:02:31,822 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:03:03,976 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:03:03,977 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:03:07,342 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:03:07,344 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:04:07,461 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:04:07,461 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:04:10,840 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:04:10,841 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:05:10,957 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:05:10,958 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:05:14,317 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:05:14,317 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:06:14,782 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:06:14,782 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:06:18,157 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:06:18,157 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:07:18,278 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:07:18,278 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:07:21,656 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:07:21,658 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:08:21,774 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:08:21,774 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:08:25,163 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:08:25,163 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:08:53,935 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:08:53,935 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:08:57,297 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:08:57,297 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:08:57,676 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:08:57,676 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:08:58,662 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 19:08:58,706 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 19:09:01,413 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:01,413 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:09:01,750 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 19:09:01,779 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:01,779 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:09:05,131 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:05,131 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:09:05,739 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:05,740 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:09:09,096 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:09,096 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:09:10,211 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:10,211 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:09:13,578 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:13,578 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:09:15,695 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:15,695 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:09:19,300 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:19,301 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:09:23,411 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:23,411 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:09:27,511 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:27,511 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:09:35,626 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:35,627 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:09:40,732 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:40,732 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:09:56,846 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:09:56,847 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:10:00,957 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:10:00,959 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:10:33,078 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:10:33,079 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:10:36,435 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:10:36,436 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:11:36,554 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:11:36,554 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:11:39,923 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:11:39,924 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:12:40,034 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:12:40,035 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:12:43,395 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:12:43,396 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:13:30,095 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:13:30,095 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:13:33,468 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:13:33,469 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:13:33,800 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 19:13:33,840 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:13:33,841 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:13:37,212 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:13:37,213 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:13:37,841 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:13:37,841 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:13:41,231 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:13:41,232 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:13:42,346 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:13:42,346 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:13:45,964 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:13:45,964 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:13:48,078 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:13:48,078 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:13:52,206 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:13:52,207 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:13:56,323 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:13:56,324 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:14:01,442 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:14:01,442 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:14:09,568 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:14:09,568 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:14:13,691 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:14:13,691 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:14:29,806 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:14:29,807 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:14:37,933 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:14:37,933 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:15:10,033 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:15:10,033 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:15:13,405 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:15:13,405 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:16:13,518 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:16:13,518 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:16:16,900 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:16:16,901 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:17:17,008 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:17:17,009 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:17:20,384 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:17:20,384 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:18:20,492 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:18:20,493 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:18:23,857 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:18:23,858 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:19:23,963 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:19:23,964 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:19:27,376 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:19:27,376 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:20:27,498 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:20:27,500 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:20:30,870 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:20:30,872 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:21:30,981 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:21:30,982 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:21:34,361 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:21:34,363 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:22:20,009 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:22:20,009 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:22:23,419 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:22:23,422 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:22:23,773 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 19:22:23,795 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:22:23,796 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:22:27,182 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:22:27,183 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:22:27,814 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:22:27,816 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:22:31,316 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:22:31,317 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:22:31,699 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:22:31,700 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:22:35,069 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:22:35,070 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:26:59,106 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:26:59,107 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:27:00,761 - root - INFO - User Legend_kr (479851312) used /start
2024-10-31 19:27:02,485 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:27:02,485 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:27:02,866 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:27:02,867 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:27:06,335 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:27:06,336 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:27:07,059 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:27:07,060 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:27:10,443 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:27:10,444 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:27:11,579 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:27:11,581 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:27:15,246 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:27:15,247 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:27:17,369 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:27:17,371 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:27:21,591 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:27:21,592 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:27:25,722 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:27:25,724 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:27:30,843 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:27:30,843 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:27:38,080 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:27:38,082 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-10-31 19:27:42,215 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-10-31 19:27:42,216 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\telegram_bot\pythonProject\.venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
2024-11-05 15:11:54,616 - root - INFO - User Legend_kr (479851312) used /start
2024-11-05 17:56:19,903 - root - INFO - User None (5679123058) used /start
2024-11-05 18:21:54,176 - root - INFO - User None (5679123058) used /start
2024-11-06 09:49:47,592 - root - INFO - User None (5679123058) used /start
2024-11-06 12:18:26,364 - root - INFO - User Legend_kr (479851312) used /start
2024-11-06 16:21:43,769 - root - INFO - User Legend_kr (479851312) used /start
2024-11-07 14:18:02,354 - root - INFO - User Legend_kr (479851312) used /start
2024-11-07 14:19:22,313 - root - INFO - User Legend_kr (479851312) used /start
2024-11-07 17:55:05,610 - root - INFO - User Legend_kr (479851312) used /start
2024-11-07 17:55:41,179 - root - INFO - User None (554980782) used /start
